# Generated by Django 4.1.7 on 2023-04-22 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0006_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='replies',
            field=models.ManyToManyField(related_name='post_replies', to='social_network.reply'),
        ),
    ]
